### ISSUE TITLE
Upstream Documentation on Tracing Kernel Subsystems

### ISSUE THREAD

**Issue by kestewart** [elisa-tech/wg-medical-devices#10]
- [x] Publish Blog on Tracing Kernel Subsystems
- [x] Establish placeholder in Linux Kernel Documentation for Analysis Support
- [x] Draft Tracing Kernel Subsystems as initial submission
- [x] Incorporate upstream feedback
- [x] Publish guide in upstream kernel documentation

**Comment by kestewart** [comment]
PR for upstream submission sent to the ELISA mailing list.

**Comment by Shefali199** [comment]
Work has been completed and upstreamed at https://docs.kernel.org/admin-guide/workload-tracing.html
